/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.json.*;
import java.util.HashMap;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

public class App {
    

    public static void main(String[] args_)
    {
         String username = "ONFON";
         String apiKey   = "4ceddd1003131a62b84796945561f28657b3c7b9ef7d8ce53ca9a2a4232293e4";
    
         String recipients = "+254724971796";
    
         String message = "We are lumberjacks. We code all day and sleep all night";
         
         // Specify your AfricasTalking shortCode or sender id
         String from = "5001";
    
         AfricasTalkingGateway gateway  = new AfricasTalkingGateway(username, apiKey);
         
        try {
            JSONArray results = gateway.sendMessage(recipients, message, from);
            
            for( int i = 0; i < results.length(); ++i ) {
                  JSONObject result = results.getJSONObject(i);
                  System.out.print(result.getString("status") + ",");
                  System.out.print(result.getString("statusCode") + ",");
                  System.out.print(result.getString("number") + ",");
                  System.out.print(result.getString("messageId") + ",");
                  System.out.println(result.getString("cost"));
        }
       }
       
       catch (Exception e) {
        System.out.println("Encountered an error while sending " + e.getMessage());
        }
    
   }
}